// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUnucbDf8rY1C1PDUrBnKrJI74vcVmmQQ',
    appId: '1:56322492879:android:098816f00370e036a56aba',
    messagingSenderId: '56322492879',
    projectId: 'openbook-68460',
    storageBucket: 'openbook-68460.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEyuIo3MiwM9snHBjWk_49gPMIrM-p-uo',
    appId: '1:56322492879:ios:db9acfd42a2a4bb1a56aba',
    messagingSenderId: '56322492879',
    projectId: 'openbook-68460',
    storageBucket: 'openbook-68460.appspot.com',
    iosBundleId: 'com.openbooks.community',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEyuIo3MiwM9snHBjWk_49gPMIrM-p-uo',
    appId: '1:56322492879:ios:d05babcfe406e16fa56aba',
    messagingSenderId: '56322492879',
    projectId: 'openbook-68460',
    storageBucket: 'openbook-68460.appspot.com',
    iosBundleId: 'com.example.openbook.RunnerTests',
  );
}
